In [106]:
import torch 
import torch.nn as nn
import torch.nn.functional as F 
from torch.autograd import Variable
import numpy as np
import cv2 
import matplotlib.pyplot as plt

In [107]:
def parse_cfg(cfgfile):
    
    file=open(cfgfile, 'r')
    lines=file.read().split('\n')
    lines=[x for x in lines if len(x)>0] #remove empty lines
    lines=[x for x in lines if x[0] !='#'] #remove commented lines
    lines = [x.rstrip().lstrip() for x in lines]
    
    block={}
    blocks=[]
    
    for line in lines:
        if line[0]=='[':
            if len(block) != 0:
                blocks.append(block)
                block = {}
            block["type"] = line[1:-1].rstrip()
            #print(block)
            
        else:
            key, value=line.split('=')
            block[key.rstrip()] = value.lstrip()
    blocks.append(block)
        
    return(blocks)

In [108]:
parse_cfg('C:/Users/tunes/Downloads/darknet-master/darknet-master/build/darknet/x64/yolov3_face.cfg')

[{'angle': '0',
  'batch': '64',
  'burn_in': '1000',
  'channels': '3',
  'decay': '0.0005',
  'exposure': '1.5',
  'height': '416',
  'hue': '.1',
  'learning_rate': '0.001',
  'max_batches': '500200',
  'momentum': '0.9',
  'policy': 'steps',
  'saturation': '1.5',
  'scales': '.1,.1',
  'steps': '400000,450000',
  'subdivisions': '16',
  'type': 'net',
  'width': '416'},
 {'activation': 'leaky',
  'batch_normalize': '1',
  'filters': '32',
  'pad': '1',
  'size': '3',
  'stride': '1',
  'type': 'convolutional'},
 {'activation': 'leaky',
  'batch_normalize': '1',
  'filters': '64',
  'pad': '1',
  'size': '3',
  'stride': '2',
  'type': 'convolutional'},
 {'activation': 'leaky',
  'batch_normalize': '1',
  'filters': '32',
  'pad': '1',
  'size': '1',
  'stride': '1',
  'type': 'convolutional'},
 {'activation': 'leaky',
  'batch_normalize': '1',
  'filters': '64',
  'pad': '1',
  'size': '3',
  'stride': '1',
  'type': 'convolutional'},
 {'activation': 'linear', 'from': '-3', 'type'

In [109]:
def get_test_input():
    img = cv2.imread("C:/Users/tunes/Downloads/test1.jpg")
    img = cv2.resize(img, (416,416)) 
    img_ =  img[:,:,::-1].transpose((2,0,1))
    img_ = img_[np.newaxis,:,:,:]/255.0
    img_ = torch.from_numpy(img_).float()
    img_ = Variable(img_)
    return img_

In [110]:
class Maxpoolstride1(nn.Module):
    
    def __inti__(self, kernel_size):
        super(Maxpoolstride1, self).__init__()
        self.kernel_size=kernel_size
        self.pad=kernel_size - 1
        
    def forward(self, x):
        padded_x=F.pad(x, (0,self.pad,0,self.pad), mode="replicate")
        pooled_x=nn.MaxPool2d(self.kernel_size, self.pad)(padded_x)
        
        return pooled_x

In [111]:
class Emptylayer(nn.Module):
    
    def __init__(self):
        super(Emptylayer, self).__init__()
       
    def forward(self, x):
        return x

In [112]:
class Detectionlayer(nn.Module):
    
    def __init__(self, anchors):
        super().__init__()
        self.anchors=anchors
        
    def forward(self, x, inp_dim, classes, confidence):
        x=x.data
        global CUDA
        prediction=x
        prediction=predict_transform(prediction, inp_dim, self.anchors, classes, confidence, CUDA)
        return prediction
        

In [113]:
class Upsample(nn.Module):
    
    def __init__(self, stride=2):
        super().__init__()
        self.stride=stride
        
    def forward(self, x):
        stride= self.stride
        assert(x.data.dim() == 4)
        B=x.data.size[0]
        C=x.data.size[1]
        H=x.data.size[2]
        W=x.data.size[3]
        ws=stride
        hs=stride
        x=x.view(B, C, H, 1, W, 1).expand(B, C, H, stride, W, stride).contiguous().view(B, C, H*stride, W*stride)
        
        return x

In [114]:
def Create_modules(blocks):
    
    net_info=blocks[0]
    
    module_list = nn.ModuleList()
    
    index = 0
    
    prev_filters = 3
    
    output_filters = []
    
    for x in blocks:
        module=nn.Sequential()
        
        if x['type'] == 'net':
            continue
            
        if x['type'] == 'convolutional':
            
            activation = x['activation']
            filters = int(x['filters'])
            padding = int(x['pad'])
            kernel_size = int(x['size'])
            stride = int(x['stride'])
            
            try:
                batch_normalize = x['batch_normalize']
                bias = False
                
            except:
                batch_normalize=0
                bias=True
            
            if padding:
                pad = (kernel_size - 1)//2
            else:
                pad = 0
                
            conv=nn.Conv2d(prev_filters, filters, kernel_size, stride, pad, bias= bias)
            module.add_module("conv_{0}".format(index), conv)
            
            
            if batch_normalize:
                bn=nn.BatchNorm2d(filters)
                module.add_module("batch_norm_{0}".format(index), bn)
                
                
            if activation=='leaky':
                activ=nn.LeakyReLU(0.1, inplace=True)
                module.add_module("leaky_{0}".format(index), activ)
                
                
        elif x['type']=='Upsample':
            stride=int(x['stride'])
            upsample=Upsample(stride)
            upsample=nn.Upsample(scale_factor=2, mode='nearest')
            module.add_module("upsample_{0}".format(index), upsample)
            
            
        elif x['type']=='route':
            layers=x['layers'].split(',')
            
            #start of a route
            
            start=int(layers[0])
            
            #end, if exists
            try:
                end=int(layers[1])
                
            except:
                end=0
                
            if start > 0:
                start=start-index
                
            if end > 0:
                end=end-index
                
            route=Emptylayer()
            module.add_module("route_{0}".format(index), route)
            
            
            if end < 0:
                filters=output_filters[index + start] + output_filters[index+end]
                
            else:
                filters=output_filters[index + start]
                
            
        elif x['type']=='shortcut':
            from_=x['from']
            shortcut=Emptylayer()
            module.add_module("shortcut_{}".format(index), shortcut)
            
            
        elif x['type']=='maxpool':
            
            stride = int(x["stride"])
            size = int(x["size"])
            
            if stride != 1:
                
                maxpool = nn.MaxPool2d(size, stride)
                
            else:
                
                maxpool = Maxpoolstride1(size)
            
            module.add_module("maxpool_{}".format(index), maxpool)
                
                
            
            
        elif x['type']=='yolo':
            mask=x['mask'].split(',')
            mask=[int(x) for x in mask]
            
            anchors=x['anchors'].split(',')
            anchors=[int(a) for a in anchors]
            anchors=[(anchors[i], anchors[i+1]) for i in range(0, len(anchors), 2)]
            anchors=[anchors[i] for i in mask]
            
            
            detection=Detectionlayer(anchors)
            module.add_module('detection_{}'.format(index), detection)
            
            
            
            
        
            
            
        module_list.append(module)
        prev_filters = filters
        output_filters.append(filters)
        index += 1
        
    
    return (net_info, module_list)
            
               

In [145]:
class Darknet(nn.Module):
    
    def __init__(self, cfgfile):
        super(Darknet, self).__init__()
        self.blocks = parse_cfg(cfgfile)
        self.net_info, self.module_list = Create_modules(self.blocks)
        self.header = torch.IntTensor([0,0,0,0])
        self.seen = 0

        
        
    def get_blocks(self):
        return self.blocks

    
    def get_module_list(self):
        return self.module_list
    
    
    
    def forward(self, x, CUDA = False):
        
        
        detections=[]
        
        modules = self.blocks[1:]
        outputs={}
        
        
        write=0
    
        
        for i in range(len(modules)):
            #print(len(modules))
            modules_type = (modules[i]['type'])
        
            if modules_type == 'convolution' or modules_type == 'upsample' or modules_type == 'maxpool' :
                x=self.modules_list[i](x)
                print(x)
                outputs[i]=x
                print(outputs[i])
            elif modules_type == 'route':
                layers = modules[i]['layers']
                layers = [int(a) for a in layers]
                
                if layers[0] > 0:
                    layers[0] = layers[0] - i
                    
                if len(layers) == 1:
                    x =  outputs[i + (layers[0])]
                    
                else:
                    if layers[1] > 0:
                        layers[1] = layers[1] - i

                    map1 = outputs [i + layers[0]]
                    map2 = outputs [i + layers[1]]
                    
                    x = torch.cat((map1, map2), 1)
                
                outputs[i] = x
                
            elif modules_type == 'shortcut':
                from_ = int(modules[i]['from'])
                print(from_)
                print(i)
                print(outputs[i-1])
                x = outputs[i-1] + outputs[i + from_]
                outputs[i] = x
                
            
            elif modules_type == 'yolo':
                
                anchors=self.module_list[i][0].anchors
                
                inp_dim=int(self.net_info['height'])
                
                num_classes=int(module[i]['classes'])
                
                x=x.data
                x=predict_transform(x, inp_dim, anchors, num_classes, CUDA)
                
                if type(x) == int:
                    continue
                    
                if not write:
                    detections = x
                    write = 1 
                    
                else:
                    detections = torch.cat((detection, x), 1)
                    
                outputs[i] = outputs[i-1]
                
                
                
        try:
            return detections
        
        except:
            return 0
        
                 
    def load_weights(self, weightfile):
        
        fp = open(weightfile, 'rb')
        
        
        header = np.fromfile(fp, dtype = np.int32, count = 5)
        self.header = torch.from_numpy(header)
        self.seen = self.header[3]
            
        
        weights = np.fromfile(fp, dtype = np.float32)
        
        ptr = 0
        
        
        
        for i in range(len(self.module_list)):
            
            module_type = self.blocks[i+1]['type']
            
            if module_type == 'convolutional':
                model = self.module_list[i]
                
                try:
                    batch_normalize = int(self.blocks[i+1]['batch_normalize'])
                    
                except:
                    batch_normalize = 0
                    
                
                conv = model[0]
                
                if batch_normalize:
                    
                    bn = model[1]
                    
                    num_bn_biases = bn.bias.numel()
                    
                    bn_biases = torch.from_numpy(weights[ptr:ptr + num_bn_biases])
                    ptr += num_bn_biases
                    
                    bn_weights = torch.from_numpy(weights[ptr:ptr + num_bn_biases])
                    ptr += num_bn_biases
                    
                    bn_running_mean = torch.from_numpy(weights[ptr:ptr + num_bn_biases])
                    ptr += num_bn_biases
                    
                    bn_running_var = torch.from_numpy(weights[ptr:ptr + num_bn_biases])
                    ptr += num_bn_biases
                    
                    bn_biases = bn_biases.view_as(bn.bias.data)
                    bn_weights = bn_weights.view_as(bn.weight.data)
                    bn_running_mean = bn_running_mean.view_as(bn.running_mean)
                    bn_running_var = bn_running_var.view_as(bn.running_var)
                    
                    
                    bn.bias.data.copy_(bn_biases)
                    bn.weight.data.copy_(bn_weights)
                    bn.running_mean.copy_(bn_running_mean)
                    bn.running_var.copy_(bn_running_var)
                    
                    
                else:
                    num_biases = conv.bias.numel()
                    
                    conv_biases = torch.from_numpy(weights[ptr:ptr  + num_biases])
                    ptr += num_biases
                    
                    conv_biases = conv_biases.view_as(conv.bias.data)
                    
                    conv.bias.data.copy_(conv_biases)
                    
                
                num_weights = conv.weight.numel()
                
                conv_weights = torch.from_numpy(weights[ptr:ptr + num_weights])
                ptr += num_weights
                #print(conv_weights.shape)
                conv_weights = conv_weights.view_as(conv.weight.data)
                
                conv.weight.data.copy_(conv_weights)
                
                
                    
    def save_weights(self, savedfile, cutoff = 0):
        
        if cutoff <= 0:
            cutoff = len(self.blocks) - 1
            
        fp = open(savedfile, 'wb')
        
        self.header[3] = self.seen
        header = self.header
        
        header = header.numpy()
        header.tofile(fp)
        
        
        for i in range(len(self.module_list)):
            module_type = self.block[i+1]['type']
            
            
            if module_type == 'convolutional':
                model = self.module_list[i]
                
                try:
                    batch_normalize = int(self.block[i+1]['batch_normalize'])
                    
                except:
                    batch_normalize = 0
                
                conv = model[0]
                
                if batch_normalize:
                    bn = model[1]
                    
                    
                    cpu(bn.bias.data).numpy().tofile(fp)
                    cpu(bn.weights.data).numpy().tofile(fp)
                    cpu(bn.running_mean).numpy().tofile(fp)
                    cpu(bn.running_var).numpy().tofile(fp)
                    
                else:
                    cpu(conv.bias.data).numpy().tofile(fp)
                    
                
                cpu(conv.weights.data).numpy().tofile(fp)
                
                
            
                    

In [146]:
a = Darknet('C:/Users/tunes/Downloads/darknet-master/darknet-master/build/darknet/x64/yolov3_face.cfg')

In [147]:
a.load_weights('C:/Users/tunes/Downloads/darknet-master/darknet-master/build/darknet/x64/yolov3.weights')

In [148]:
inp = get_test_input()

In [149]:
s,d = a(inp)

-3
4


KeyError: 3

In [120]:
a.eval()

Darknet(
  (module_list): ModuleList(
    (0): Sequential(
      (conv_0): Conv2d(3, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (batch_norm_0): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (leaky_0): LeakyReLU(negative_slope=0.1, inplace)
    )
    (1): Sequential(
      (conv_1): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
      (batch_norm_1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (leaky_1): LeakyReLU(negative_slope=0.1, inplace)
    )
    (2): Sequential(
      (conv_2): Conv2d(64, 32, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (batch_norm_2): BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (leaky_2): LeakyReLU(negative_slope=0.1, inplace)
    )
    (3): Sequential(
      (conv_3): Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (batch_norm_3): Batch

In [ ]:
outputs[3]

In [140]:
class Darknet(nn.Module):
    def __init__(self, cfgfile):
        super(Darknet, self).__init__()
        self.blocks = parse_cfg(cfgfile)
        self.net_info, self.module_list = Create_modules(self.blocks)
        self.header = torch.IntTensor([0,0,0,0])
        self.seen = 0

        
        
    def get_blocks(self):
        return self.blocks
    
    def get_module_list(self):
        return self.module_list

                
    def forward(self, x, CUDA=False):
        detections = []
        modules = self.blocks[1:]
        outputs = {}   #We cache the outputs for the route layer
        
        
        write = 0
        for i in range(len(modules)):        
            
            module_type = (modules[i]["type"])
            if module_type == "convolutional" or module_type == "upsample" or module_type == "maxpool":
                
                x = self.module_list[i](x)
                outputs[i] = x
                print(outputs[i])
                
            elif module_type == "route":
                layers = modules[i]["layers"]
                layers = [int(a) for a in layers]
                
                if (layers[0]) > 0:
                    layers[0] = layers[0] - i

                if len(layers) == 1:
                    x = outputs[i + (layers[0])]

                else:
                    if (layers[1]) > 0:
                        layers[1] = layers[1] - i
                        
                    map1 = outputs[i + layers[0]]
                    map2 = outputs[i + layers[1]]
                    
                    
                    x = torch.cat((map1, map2), 1)
                outputs[i] = x
            
            elif  module_type == "shortcut":
                from_ = int(modules[i]["from"])
                x = outputs[i-1] + outputs[i+from_]
                outputs[i] = x
                
            
            
            elif module_type == 'yolo':        
                
                anchors = self.module_list[i][0].anchors
                #Get the input dimensions
                inp_dim = int (self.net_info["height"])
                
                #Get the number of classes
                num_classes = int (modules[i]["classes"])
                
                #Output the result
                x = x.data
                x = predict_transform(x, inp_dim, anchors, num_classes, CUDA)
                
                if type(x) == int:
                    continue

                
                if not write:
                    detections = x
                    write = 1
                
                else:
                    detections = torch.cat((detections, x), 1)
                
                outputs[i] = outputs[i-1]
                
        
        
        try:
            return detections
        except:
            return 0

            
    def load_weights(self, weightfile):
        
        #Open the weights file
        fp = open(weightfile, "rb")

        #The first 4 values are header information 
        # 1. Major version number
        # 2. Minor Version Number
        # 3. Subversion number 
        # 4. IMages seen 
        header = np.fromfile(fp, dtype = np.int32, count = 5)
        self.header = torch.from_numpy(header)
        self.seen = self.header[3]
        
        #The rest of the values are the weights
        # Let's load them up
        weights = np.fromfile(fp, dtype = np.float32)
        
        ptr = 0
        for i in range(len(self.module_list)):
            module_type = self.blocks[i + 1]["type"]
            
            if module_type == "convolutional":
                model = self.module_list[i]
                try:
                    batch_normalize = int(self.blocks[i+1]["batch_normalize"])
                except:
                    batch_normalize = 0
                
                conv = model[0]
                
                if (batch_normalize):
                    bn = model[1]
                    
                    #Get the number of weights of Batch Norm Layer
                    num_bn_biases = bn.bias.numel()
                    
                    #Load the weights
                    bn_biases = torch.from_numpy(weights[ptr:ptr + num_bn_biases])
                    ptr += num_bn_biases
                    
                    bn_weights = torch.from_numpy(weights[ptr: ptr + num_bn_biases])
                    ptr  += num_bn_biases
                    
                    bn_running_mean = torch.from_numpy(weights[ptr: ptr + num_bn_biases])
                    ptr  += num_bn_biases
                    
                    bn_running_var = torch.from_numpy(weights[ptr: ptr + num_bn_biases])
                    ptr  += num_bn_biases
                    
                    #Cast the loaded weights into dims of model weights. 
                    bn_biases = bn_biases.view_as(bn.bias.data)
                    bn_weights = bn_weights.view_as(bn.weight.data)
                    bn_running_mean = bn_running_mean.view_as(bn.running_mean)
                    bn_running_var = bn_running_var.view_as(bn.running_var)

                    #Copy the data to model
                    bn.bias.data.copy_(bn_biases)
                    bn.weight.data.copy_(bn_weights)
                    bn.running_mean.copy_(bn_running_mean)
                    bn.running_var.copy_(bn_running_var)
                
                else:
                    #Number of biases
                    num_biases = conv.bias.numel()
                
                    #Load the weights
                    conv_biases = torch.from_numpy(weights[ptr: ptr + num_biases])
                    ptr = ptr + num_biases
                    
                    #reshape the loaded weights according to the dims of the model weights
                    conv_biases = conv_biases.view_as(conv.bias.data)
                    
                    #Finally copy the data
                    conv.bias.data.copy_(conv_biases)
                    
                    
                #Let us load the weights for the Convolutional layers
                num_weights = conv.weight.numel()
                
                #Do the same as above for weights
                conv_weights = torch.from_numpy(weights[ptr:ptr+num_weights])
                ptr = ptr + num_weights

                conv_weights = conv_weights.view_as(conv.weight.data)
                conv.weight.data.copy_(conv_weights)
                
    def save_weights(self, savedfile, cutoff = 0):
            
        if cutoff <= 0:
            cutoff = len(self.blocks) - 1
        
        fp = open(savedfile, 'wb')
        
        # Attach the header at the top of the file
        self.header[3] = self.seen
        header = self.header

        header = header.numpy()
        header.tofile(fp)
        
        # Now, let us save the weights 
        for i in range(len(self.module_list)):
            module_type = self.blocks[i+1]["type"]
            
            if (module_type) == "convolutional":
                model = self.module_list[i]
                try:
                    batch_normalize = int(self.blocks[i+1]["batch_normalize"])
                except:
                    batch_normalize = 0
                    
                conv = model[0]

                if (batch_normalize):
                    bn = model[1]
                
                    #If the parameters are on GPU, convert them back to CPU
                    #We don't convert the parameter to GPU
                    #Instead. we copy the parameter and then convert it to CPU
                    #This is done as weight are need to be saved during training
                    cpu(bn.bias.data).numpy().tofile(fp)
                    cpu(bn.weight.data).numpy().tofile(fp)
                    cpu(bn.running_mean).numpy().tofile(fp)
                    cpu(bn.running_var).numpy().tofile(fp)
                
            
                else:
                    cpu(conv.bias.data).numpy().tofile(fp)
                
                
                #Let us save the weights for the Convolutional layers
                cpu(conv.weight.data).numpy().tofile(fp)
               





In [141]:
v = Darknet('C:/Users/tunes/Downloads/darknet-master/darknet-master/build/darknet/x64/yolov3_face.cfg')

In [142]:
v.load_weights('C:/Users/tunes/Downloads/darknet-master/darknet-master/build/darknet/x64/yolov3.weights')

In [143]:
inp = get_test_input()

In [144]:
s,d = v(inp)

tensor([[[[-5.8882e-01, -4.4997e-01, -4.4997e-01,  ..., -5.0809e-01,
           -5.0809e-01, -7.1135e-01],
          [-5.7352e-01, -4.7806e-01, -4.7806e-01,  ..., -5.4145e-01,
           -5.4145e-01, -6.5045e-01],
          [-5.7352e-01, -4.7806e-01, -4.7806e-01,  ..., -5.4145e-01,
           -5.4145e-01, -6.5045e-01],
          ...,
          [-6.3449e-01, -6.1667e-01, -7.2394e-01,  ..., -3.5784e-01,
           -4.5045e-01, -4.7052e-01],
          [-6.6337e-01, -6.4690e-01, -7.7161e-01,  ..., -4.7893e-01,
           -4.4996e-01, -5.1638e-01],
          [ 3.5957e+00,  4.5302e+00,  4.7132e+00,  ...,  3.9828e+00,
            4.1806e+00,  3.6565e+00]],

         [[ 1.7955e+00,  1.3114e+00,  1.3114e+00,  ...,  1.1926e+00,
            1.1926e+00,  7.5540e-01],
          [ 8.3093e-01, -1.0679e-01, -1.0679e-01,  ..., -1.3527e-01,
           -1.3527e-01, -2.0244e-01],
          [ 8.3093e-01, -1.0679e-01, -1.0679e-01,  ..., -1.3527e-01,
           -1.3527e-01, -2.0244e-01],
          ...,
     

tensor([[[[-5.7650e-01, -4.3203e-01, -2.5474e-01,  ..., -2.6528e-01,
           -4.1470e-01, -3.3949e-01],
          [-7.8383e-01, -1.0505e-01,  3.2922e-01,  ...,  2.2844e-01,
            8.5964e-01, -2.5114e-01],
          [-9.5648e-01, -1.1966e-01,  1.2516e-01,  ...,  1.8131e-01,
            1.1817e+00, -1.2121e-01],
          ...,
          [-9.9658e-01, -1.7283e-01,  3.9855e-01,  ...,  8.5586e-01,
           -2.0488e-02, -6.1092e-02],
          [-9.2253e-01, -7.0162e-02,  1.4136e+00,  ..., -2.6020e-01,
            1.7583e-01,  1.2422e-01],
          [-6.9387e-01,  8.2176e-01,  8.4928e-01,  ..., -3.1115e-01,
            2.7862e+00, -5.9538e-02]],

         [[-3.0202e-02, -4.1234e-02, -3.6963e-02,  ..., -3.6978e-02,
           -4.1526e-02, -4.0469e-02],
          [-4.3657e-02, -6.5657e-02, -5.9313e-02,  ..., -6.0614e-02,
           -6.6180e-02, -5.5159e-02],
          [-2.5219e-02, -3.6952e-02, -3.4383e-02,  ..., -3.4489e-02,
           -4.0206e-02, -3.4493e-02],
          ...,
     

tensor([[[[-4.2600e-02, -4.2597e-02, -4.2596e-02,  ..., -4.2596e-02,
           -4.2596e-02, -4.2598e-02],
          [-4.2600e-02, -4.2591e-02, -4.2590e-02,  ..., -4.2591e-02,
           -4.2590e-02, -4.2593e-02],
          [-4.2603e-02, -4.2596e-02, -4.2595e-02,  ..., -4.2597e-02,
           -4.2596e-02, -4.2596e-02],
          ...,
          [-4.2602e-02, -4.2597e-02, -4.2600e-02,  ..., -4.2598e-02,
           -4.2598e-02, -4.2598e-02],
          [-4.2603e-02, -4.2598e-02, -4.2600e-02,  ..., -4.2598e-02,
           -4.2596e-02, -4.2599e-02],
          [-4.2601e-02, -4.2598e-02, -4.2599e-02,  ..., -4.2599e-02,
           -4.2599e-02, -4.2600e-02]],

         [[ 1.1728e-01, -1.4781e-01, -2.1588e-01,  ..., -2.3388e-01,
           -1.9953e-01, -7.4049e-02],
          [-1.4385e-01, -3.2297e-01, -3.0499e-01,  ..., -3.3141e-01,
           -3.1916e-01, -1.7557e-01],
          [ 1.9708e+00, -1.5638e-02,  9.6895e-02,  ...,  9.6020e-02,
           -2.8066e-03,  6.0443e-01],
          ...,
     

tensor([[[[-1.2788e-01, -7.7600e-02, -1.0591e-01,  ..., -1.1265e-01,
           -1.1812e-01, -1.0993e-01],
          [-1.4276e-02,  1.0240e+00,  9.1179e-02,  ...,  5.4977e-01,
            3.7657e-01,  7.7973e-02],
          [-3.2397e-02,  1.1213e+00,  2.1177e-01,  ...,  5.4165e-01,
            5.0898e-01,  2.4606e-01],
          ...,
          [-5.3809e-03,  1.1311e+00,  5.1657e-01,  ...,  3.9832e-01,
           -6.8571e-02,  1.2562e+00],
          [ 5.3977e-01,  6.6747e-01,  1.6850e+00,  ..., -4.9445e-02,
            3.0982e-02,  1.7654e+00],
          [-1.2843e-01,  1.2968e+00,  1.1591e+00,  ..., -7.6823e-02,
            1.1455e+00,  8.4822e-01]],

         [[-7.6675e-02,  3.8869e-02,  1.9400e-01,  ...,  2.6419e-01,
            2.8338e-01,  1.6577e+00],
          [-3.2431e-01, -7.1823e-02, -5.7909e-02,  ..., -5.0659e-02,
           -6.8208e-02,  8.3847e-01],
          [-3.2398e-01, -6.0506e-02, -2.3101e-02,  ..., -3.8660e-02,
           -4.3598e-02,  9.2977e-01],
          ...,
     

tensor([[[[ 3.0289e+00,  5.2452e+00,  4.8460e+00,  ...,  4.9301e+00,
            4.9398e+00,  4.4597e+00],
          [ 1.0767e+00,  8.3544e-01,  1.0890e-01,  ...,  2.3427e-02,
            1.1826e-01, -5.4637e-02],
          [ 5.2007e-01, -1.5467e-02, -5.2631e-02,  ..., -4.5715e-02,
           -3.6194e-02, -7.2010e-02],
          ...,
          [ 2.5707e-01, -9.7561e-02, -1.9646e-01,  ..., -8.3262e-02,
           -9.4104e-02, -1.2768e-01],
          [-1.0815e-02, -1.4983e-01, -1.5056e-01,  ..., -1.3236e-01,
           -1.0941e-01, -1.1916e-01],
          [-1.7845e-01, -2.1171e-01, -8.2393e-02,  ..., -1.4046e-01,
           -1.0757e-01, -2.2161e-01]],

         [[ 2.6343e+00,  2.9772e+00,  2.6691e+00,  ...,  2.8322e+00,
            2.9738e+00,  4.1315e+00],
          [-1.6827e-01, -2.2406e-02,  4.0090e-02,  ..., -5.1588e-03,
           -1.7364e-02, -4.0074e-02],
          [-1.6613e-01,  7.0051e-02, -1.2181e-02,  ..., -2.5794e-02,
           -2.1393e-02, -3.7378e-02],
          ...,
     

tensor([[[[ 1.6457e-01, -1.7400e-01, -6.1727e-02,  ..., -8.4683e-02,
           -8.5320e-02, -5.1439e-02],
          [-3.5869e-02, -1.2338e-01, -1.1369e-01,  ..., -1.9011e-01,
           -2.0587e-01, -1.2006e-01],
          [-3.2516e-02,  2.0687e-01, -5.0006e-02,  ..., -1.3703e-01,
           -1.6464e-01, -9.0105e-02],
          ...,
          [-3.5373e-02,  3.3623e-01, -1.3629e-02,  ..., -1.5912e-02,
            3.1645e-01, -3.7748e-02],
          [ 5.3392e-02,  2.3739e-01, -1.5336e-01,  ...,  3.3183e-01,
           -9.6236e-02, -1.7978e-02],
          [ 5.5394e-01, -4.8721e-02, -1.3140e-01,  ..., -2.9615e-02,
           -3.3428e-02, -5.5876e-03]],

         [[-2.1272e-01, -2.6121e-01, -1.6545e-01,  ..., -1.1628e-01,
           -7.1940e-02, -8.1544e-02],
          [ 1.2074e-01, -1.6132e-01, -1.6549e-01,  ..., -1.1950e-01,
           -6.3222e-02, -1.8458e-01],
          [ 2.8228e-01, -4.8924e-02, -3.0897e-03,  ...,  5.4269e-01,
            6.6204e-01, -8.8750e-02],
          ...,
     

tensor([[[[-5.3747e-02, -3.2837e-02, -4.5990e-02,  ..., -3.9686e-02,
           -1.5323e-02,  1.1196e+00],
          [ 2.4088e-01, -3.4925e-02,  2.4706e-01,  ...,  3.7766e-01,
            3.7433e-01,  8.1443e-01],
          [ 5.5629e-01, -5.4981e-03,  5.0438e-01,  ...,  3.0063e-01,
            3.6914e-01,  1.5097e+00],
          ...,
          [ 7.4976e-01,  9.4929e-01,  1.0874e+00,  ...,  1.3363e+00,
            1.2648e+00,  1.8117e+00],
          [ 3.8230e-01,  9.9761e-01,  1.0166e+00,  ...,  1.7064e+00,
            2.0479e+00,  2.0672e+00],
          [ 9.1492e-01,  1.6573e+00,  1.2198e+00,  ...,  2.3619e+00,
            2.0870e+00,  2.1515e+00]],

         [[-3.2853e-01, -2.9645e-01, -2.5540e-01,  ..., -2.0498e-01,
           -1.6216e-01, -2.1488e-03],
          [-2.7999e-01, -2.3776e-01, -2.4920e-01,  ..., -2.1130e-01,
           -1.6518e-01, -1.5379e-01],
          [-2.2293e-01, -7.5634e-02, -1.0392e-01,  ..., -6.4222e-02,
            6.6748e-02,  1.7948e-01],
          ...,
     

tensor([[[[ 1.5283e+00, -3.6570e-01, -2.2634e-01,  ..., -1.7196e-01,
           -2.7065e-01, -3.4730e-01],
          [-9.5535e-02, -4.4651e-01, -2.5762e-01,  ..., -2.1454e-01,
           -2.5560e-01, -2.5004e-01],
          [-7.4231e-02, -3.0844e-01, -1.4242e-01,  ..., -1.4238e-01,
           -4.4654e-02, -1.5555e-01],
          ...,
          [ 4.7745e-01, -4.3547e-02, -3.2640e-02,  ..., -6.3484e-02,
            5.7755e-01, -1.8988e-01],
          [ 1.2871e+00,  8.6440e-01, -6.8027e-02,  ...,  7.4463e-01,
           -8.4200e-02, -1.6551e-01],
          [ 1.8396e+00,  1.0704e+00, -1.1067e-01,  ...,  3.6268e-01,
           -1.1927e-01,  1.3362e+00]],

         [[-9.8706e-02, -7.8215e-02, -1.0144e-01,  ..., -9.2406e-02,
           -3.9385e-02, -6.6960e-03],
          [-1.1293e-01, -5.9320e-02, -8.3135e-02,  ..., -8.5578e-02,
           -4.1367e-02,  8.8827e-03],
          [-9.1243e-02, -6.7380e-02, -8.2708e-02,  ..., -7.8032e-02,
           -7.0443e-02, -5.9092e-02],
          ...,
     

tensor([[[[-2.9606e-01, -1.1227e-01, -2.2641e-01,  ..., -1.9669e-01,
           -2.2899e-01, -9.8311e-02],
          [-1.2818e-01,  4.1615e-01, -3.0450e-02,  ..., -7.0562e-02,
            2.0326e-01,  6.5950e-01],
          [-2.2145e-01, -3.8631e-02,  2.4607e-01,  ..., -4.6937e-02,
           -7.4465e-02, -3.4784e-02],
          ...,
          [-2.4364e-02, -4.2872e-02, -1.3029e-01,  ..., -1.8441e-01,
            1.7141e-01,  9.1754e-01],
          [-2.8780e-02, -1.0630e-01,  1.3854e+00,  ..., -3.1707e-02,
           -1.1451e-02, -2.6394e-01],
          [ 1.1826e-01,  8.8429e-01,  2.3331e+00,  ...,  1.8667e+00,
            1.6965e-01,  6.1002e-01]],

         [[-2.4405e-01, -2.8455e-01, -3.2484e-01,  ..., -3.1930e-01,
           -3.9985e-01, -2.1267e-02],
          [-1.9317e-01, -8.4514e-02, -1.2950e-01,  ..., -1.0901e-01,
           -9.2492e-02, -6.2606e-02],
          [-9.1110e-02, -2.2592e-02, -6.0006e-02,  ..., -2.8704e-02,
           -2.3487e-02, -3.5366e-02],
          ...,
     

tensor([[[[-2.5176e-02,  8.3731e-01,  1.2163e+00,  ...,  1.4549e+00,
            1.4626e+00, -1.0299e-01],
          [ 1.6024e+00, -4.2961e-03,  3.7467e-01,  ...,  9.6096e-02,
            8.8152e-01,  9.5593e-01],
          [ 1.7702e+00, -2.1424e-02,  7.1829e-01,  ...,  6.4382e-01,
            1.0986e+00,  1.0594e+00],
          ...,
          [ 7.8172e-01, -5.9049e-02, -2.6439e-02,  ..., -1.9216e-01,
           -1.5513e-01, -5.9039e-02],
          [ 3.9168e-01, -1.6021e-02, -7.5627e-02,  ..., -1.7162e-01,
           -1.9144e-01, -7.6313e-02],
          [ 4.4470e-01, -1.0005e-01, -1.8669e-01,  ..., -1.2400e-01,
           -7.1115e-02, -8.6348e-02]],

         [[ 7.8565e-01, -2.1903e-02, -4.1162e-02,  ..., -5.8061e-02,
           -4.9796e-02, -8.9442e-02],
          [ 8.6670e-01,  4.5951e-01, -1.2638e-02,  ..., -5.2552e-02,
           -1.9150e-02,  9.0638e-02],
          [ 1.0641e+00,  3.4024e-01, -2.4132e-02,  ...,  2.6546e-01,
            2.4453e-01, -2.3177e-02],
          ...,
     

tensor([[[[-4.2118e-02,  1.3492e+00, -7.4353e-03,  ..., -1.6823e-03,
            7.5033e-02, -9.7227e-03],
          [-4.5268e-02,  1.4696e+00, -2.2379e-02,  ..., -7.9997e-03,
           -3.5978e-02,  1.1828e-01],
          [-3.8807e-02, -2.1682e-02, -4.6934e-02,  ..., -2.0647e-02,
           -1.2401e-02,  1.7006e-01],
          ...,
          [-1.4492e-02,  1.8170e-01, -9.3061e-02,  ..., -1.3099e-01,
           -1.4595e-01, -1.5593e-01],
          [-1.7614e-02, -3.8543e-03, -9.2464e-02,  ..., -1.6424e-01,
           -1.2455e-01, -1.3605e-01],
          [-6.0113e-02,  2.2602e-01, -6.6264e-02,  ..., -9.6603e-02,
           -6.1815e-02, -2.4364e-02]],

         [[-6.9513e-02, -6.5235e-02, -6.1902e-02,  ..., -5.7880e-02,
           -6.2011e-02, -5.7724e-02],
          [-7.0893e-02, -6.3389e-02, -6.4848e-02,  ..., -5.9574e-02,
           -6.2754e-02, -5.9496e-02],
          [-6.8044e-02, -6.3573e-02, -5.7421e-02,  ..., -5.2032e-02,
           -5.4262e-02, -5.5832e-02],
          ...,
     

tensor([[[[-7.3961e-02, -1.3394e-01, -1.2186e-01,  ..., -9.2903e-02,
           -1.0300e-01, -2.2309e-01],
          [-2.6713e-02,  2.3806e-02, -1.6719e-02,  ..., -1.2451e-02,
            5.8187e-01,  4.5559e-01],
          [-7.6812e-02,  3.4940e-01, -2.5892e-02,  ..., -3.7310e-02,
            2.8590e-01,  1.3859e-01],
          ...,
          [-1.0359e-01,  3.8038e-02, -7.0251e-02,  ..., -5.9033e-02,
           -5.9082e-02, -4.9863e-02],
          [-4.1503e-02, -6.5776e-02, -7.5879e-02,  ..., -5.2800e-02,
           -1.3479e-01, -2.8557e-02],
          [-9.1493e-02, -2.0619e-01, -2.3868e-01,  ..., -1.2534e-01,
           -2.5023e-01, -1.1995e-01]],

         [[-1.1038e-01,  3.0955e-01,  7.2718e-01,  ...,  5.7831e-01,
           -2.4073e-02, -2.1544e-02],
          [-1.4919e-01, -7.3913e-02, -5.4772e-02,  ..., -8.4554e-02,
           -1.1370e-01, -1.8921e-02],
          [-6.3353e-02, -5.3636e-02, -9.9067e-02,  ..., -9.4968e-02,
           -4.0015e-02, -4.1889e-02],
          ...,
     

tensor([[[[-6.3152e-02, -6.8065e-02, -1.8871e-01,  ..., -1.1116e-01,
           -1.5368e-01,  3.0611e-01],
          [-2.7026e-02,  3.6571e+00, -1.2456e-01,  ..., -5.7814e-02,
           -1.3428e-01, -1.1390e-02],
          [-7.6703e-02,  2.2656e+00,  2.1387e-02,  ..., -5.7109e-02,
           -7.2824e-02, -5.0659e-02],
          ...,
          [-1.2610e-01, -5.3821e-02, -1.1430e-01,  ..., -1.7445e-01,
           -1.3058e-01,  5.0909e-01],
          [-5.2461e-02, -1.5779e-01, -2.1868e-01,  ..., -1.0208e-01,
           -1.2515e-01, -2.9129e-02],
          [-8.5095e-02, -1.4189e-01, -1.8979e-01,  ..., -9.4051e-02,
           -1.6411e-01, -8.9281e-02]],

         [[-5.9141e-01, -2.8659e-01,  1.2783e+00,  ...,  3.9944e-01,
            5.4795e-01, -3.4686e-01],
          [-7.3339e-01, -3.8658e-01,  6.6012e-01,  ..., -4.1141e-02,
           -9.6071e-02, -3.7556e-01],
          [-2.6332e-01, -3.5154e-01, -2.2833e-01,  ..., -1.4462e-01,
            1.4892e-01, -6.3104e-02],
          ...,
     

tensor([[[[ 5.8140e-01, -8.5558e-02, -7.4602e-02,  ..., -2.9380e-02,
           -2.0282e-01, -3.1077e-02],
          [-3.1049e-01, -1.2057e-01, -8.9923e-02,  ..., -4.7911e-02,
           -2.2451e-01, -9.7428e-02],
          [-7.7545e-02, -1.3777e-01, -8.4557e-02,  ...,  4.0590e-01,
           -2.3130e-02,  8.8158e-01],
          ...,
          [ 1.2452e+00,  5.6899e-02, -2.9443e-02,  ..., -9.4270e-02,
           -6.3852e-02,  3.6057e-01],
          [ 1.1942e-01, -3.2282e-02,  6.4201e-01,  ..., -1.5089e-01,
            1.1243e-01,  1.4927e-02],
          [-2.6057e-02,  7.6908e-01,  7.9705e-01,  ..., -4.7138e-02,
            3.1377e-01,  1.1579e-01]],

         [[-2.8965e-01,  1.9694e+00,  4.1903e-01,  ..., -3.3141e-02,
           -2.6640e-01, -1.8326e-02],
          [-2.9767e-01, -2.6161e-01, -2.8088e-02,  ..., -8.7988e-02,
           -2.9929e-01, -1.6311e-01],
          [-5.4444e-02, -1.1957e-01, -4.6363e-03,  ..., -3.5766e-02,
           -8.6732e-02, -2.9073e-02],
          ...,
     

tensor([[[[ 7.4030e-01, -6.4256e-01, -7.0947e-02,  ...,  9.3602e-01,
           -1.8354e-01,  1.5954e+00],
          [-2.5691e-01, -2.5498e-01, -8.1281e-02,  ..., -8.5342e-02,
           -2.6714e-01, -1.6545e-01],
          [ 9.5076e-01,  1.8489e-01, -1.4787e-02,  ...,  2.5763e-01,
           -5.3684e-02,  3.3979e-01],
          ...,
          [-3.7002e-02, -7.0665e-02, -1.2178e-02,  ..., -9.6191e-02,
           -9.7541e-02, -5.0915e-02],
          [-4.7333e-02, -9.0803e-02,  8.0189e-01,  ..., -6.4808e-02,
           -8.2058e-02, -5.8685e-03],
          [ 7.2142e-01, -7.6003e-02, -4.9990e-02,  ..., -9.6771e-02,
           -1.4881e-01, -4.2493e-02]],

         [[-8.0100e-01, -1.1441e+00, -9.2651e-02,  ..., -6.9244e-02,
            5.1120e+00, -1.9711e-01],
          [-4.7310e-01, -6.0631e-01,  1.4366e-01,  ..., -6.8309e-02,
            1.4999e+00, -3.5505e-01],
          [-1.0635e-01, -1.5732e-01, -5.8074e-02,  ..., -5.5421e-02,
           -7.9976e-03, -1.9828e-01],
          ...,
     

tensor([[[[-3.0542e-02, -3.0588e-02, -3.0564e-02,  ..., -3.0565e-02,
           -3.0565e-02, -3.0560e-02],
          [-3.0549e-02, -3.0572e-02, -3.0565e-02,  ..., -3.0566e-02,
           -3.0564e-02, -3.0561e-02],
          [-3.0559e-02, -3.0570e-02, -3.0565e-02,  ..., -3.0565e-02,
           -3.0565e-02, -3.0563e-02],
          ...,
          [-3.0562e-02, -3.0568e-02, -3.0563e-02,  ..., -3.0565e-02,
           -3.0565e-02, -3.0563e-02],
          [-3.0560e-02, -3.0569e-02, -3.0564e-02,  ..., -3.0564e-02,
           -3.0565e-02, -3.0562e-02],
          [-3.0559e-02, -3.0567e-02, -3.0563e-02,  ..., -3.0563e-02,
           -3.0564e-02, -3.0561e-02]],

         [[-3.0080e-02, -2.7863e-02, -2.8065e-02,  ..., -2.8140e-02,
           -2.8271e-02, -2.8513e-02],
          [-2.9596e-02, -2.7578e-02, -2.7855e-02,  ..., -2.8010e-02,
           -2.7981e-02, -2.8349e-02],
          [-2.8583e-02, -2.7931e-02, -2.7878e-02,  ..., -2.8052e-02,
           -2.7976e-02, -2.8089e-02],
          ...,
     

tensor([[[[ 1.0489e+00, -5.6942e-02,  3.2751e-01,  ..., -1.4751e-02,
            1.1539e-02,  1.3852e-01],
          [-1.3953e-01,  2.8774e-01, -4.7084e-02,  ..., -8.4606e-02,
           -1.6947e-01, -1.4364e-01],
          [-2.7037e-02, -8.8080e-02, -4.7476e-02,  ..., -6.9891e-02,
           -2.7679e-02,  8.4810e-03],
          ...,
          [-5.4300e-02, -6.8117e-02, -5.5993e-02,  ...,  1.1405e+00,
            2.0720e-01, -6.8724e-03],
          [-7.5362e-02, -5.7161e-03,  2.7521e-02,  ..., -1.6829e-02,
           -5.5258e-02, -8.4722e-02],
          [-1.7233e-02,  3.8528e-01,  4.8964e-02,  ..., -9.5954e-03,
           -9.5290e-02, -7.1539e-02]],

         [[-4.6870e-02, -4.6870e-02, -4.6870e-02,  ..., -4.6870e-02,
           -4.6870e-02, -4.6870e-02],
          [-4.6870e-02, -4.6870e-02, -4.6870e-02,  ..., -4.6870e-02,
           -4.6870e-02, -4.6870e-02],
          [-4.6870e-02, -4.6870e-02, -4.6870e-02,  ..., -4.6870e-02,
           -4.6870e-02, -4.6870e-02],
          ...,
     

tensor([[[[-4.9782e-01, -3.9229e-01, -1.9630e-01,  ..., -1.8918e-01,
            1.3303e+00,  4.1950e-01],
          [-1.4710e-01, -1.6978e-01, -1.4819e-01,  ..., -1.1526e-01,
            1.3559e+00, -1.6967e-01],
          [-1.0361e-01, -6.5466e-02,  1.8294e-01,  ..., -5.1074e-02,
            9.3520e-01, -8.8662e-02],
          ...,
          [ 1.0679e+00,  1.4663e+00,  5.7086e-01,  ..., -1.4064e-01,
           -1.2327e-01, -5.6309e-02],
          [ 6.5262e-01,  4.6694e-01, -2.5927e-02,  ..., -6.6461e-02,
           -7.3145e-02, -4.2268e-02],
          [ 6.0990e-01,  6.4811e-01,  4.2895e-02,  ...,  5.3250e-01,
            3.6178e-01,  1.8646e-01]],

         [[ 2.7876e+00, -1.7432e-01,  2.4163e+00,  ...,  1.6301e+00,
            4.5653e+00,  1.8402e+00],
          [ 7.8313e-02, -2.1206e-01,  2.1819e+00,  ..., -4.4557e-02,
            3.7131e+00,  1.1623e+00],
          [ 1.1264e+00, -1.7622e-02,  1.2567e+00,  ...,  1.0709e-02,
            1.6713e+00,  4.4696e-01],
          ...,
     

tensor([[[[-2.2105e-01, -1.6179e-01,  2.2444e+00,  ..., -4.1723e-02,
           -7.5843e-02,  8.7937e-01],
          [-2.7201e-01, -1.5782e-01,  3.1998e+00,  ..., -2.1926e-01,
           -2.7360e-01,  2.5104e+00],
          [ 6.6549e-01, -1.1780e-02,  2.4897e+00,  ..., -1.2720e-01,
            2.5346e-01,  2.3744e+00],
          ...,
          [-5.2743e-02,  1.0381e-01, -1.9756e-02,  ...,  3.7924e+00,
            2.3115e+00,  1.2725e-01],
          [-7.8023e-02, -6.1006e-02, -7.3012e-02,  ...,  3.6563e+00,
            1.6275e+00,  1.4185e-01],
          [-8.7246e-02, -6.4012e-02, -4.4447e-02,  ...,  1.9633e+00,
            8.8069e-01, -7.7484e-03]],

         [[ 1.6140e+00, -1.7991e-01, -3.6764e-01,  ...,  2.3774e+00,
            8.9340e-01,  4.6449e-01],
          [ 4.4090e+00, -1.6601e-01, -5.2119e-01,  ...,  9.4817e-01,
            1.7185e+00,  9.4948e-01],
          [ 2.9686e+00, -1.9450e-01, -3.3475e-01,  ...,  3.1584e-01,
           -1.8358e-02, -5.8823e-02],
          ...,
     

NameError: name 'predict_transform' is not defined